// 12 个月度主题配置
// 每月一套主题（标题/标语/话题标签/品牌色/图标/明信片纸色）+ 差异化相框大字文案
// 默认为 9 月「Share Your Destination」，顶部下拉或首页画廊可切换任意月份。

export const FRAME_TYPES = ["route", "postcard", "window"];

export const THEMES = [
  {
    month: 1,
    name: "一月",
    season: "WINTER",
    title: "NEW YEAR HORIZON",
    tagline: "Every new road is a new beginning.",
    hashtags: ["#KaiyiLifeInMotion", "#NewYearHorizon"],
    accent: "#6ce26a",
    bg: "#1b2b4a",
    icon: "fireworks",
    paper: "#eef2f7",
    frameLabels: { route: "MY NEXT STOP", postcard: "POSTCARD FROM", window: "VIEW FROM MY JOURNEY" },
    copy: { stop: "FIRST STOP OF THE YEAR", place: "MY NEW HORIZON", view: "VIEW FROM MY NEW ROAD" },
  },
  {
    month: 2,
    name: "二月",
    season: "SPRING",
    title: "CHERRY BLOSSOM ROAD",
    tagline: "Drive through the pink season.",
    hashtags: ["#KaiyiLifeInMotion", "#CherryBlossomRoad"],
    accent: "#f2a0b5",
    bg: "#3a2433",
    icon: "blossom",
    paper: "#faf0f3",
    frameLabels: { route: "MY NEXT STOP", postcard: "POSTCARD FROM", window: "VIEW FROM MY JOURNEY" },
    copy: { stop: "NEXT BLOSSOM STOP", place: "MY BLOSSOM ROAD", view: "VIEW FROM PETAL SEASON" },
  },
  {
    month: 3,
    name: "三月",
    season: "SPRING",
    title: "SPRING EXPEDITION",
    tagline: "Adventure, freshly bloomed.",
    hashtags: ["#KaiyiLifeInMotion", "#SpringExpedition"],
    accent: "#7ed957",
    bg: "#22301d",
    icon: "sprout",
    paper: "#eef6e8",
    frameLabels: { route: "MY NEXT STOP", postcard: "POSTCARD FROM", window: "VIEW FROM MY JOURNEY" },
    copy: { stop: "MY NEXT TRAILHEAD", place: "MY SPRING EXPEDITION", view: "VIEW FROM THE WILD" },
  },
  {
    month: 4,
    name: "四月",
    season: "SPRING",
    title: "CITY ESCAPE",
    tagline: "Chase the skyline, keep the freedom.",
    hashtags: ["#KaiyiLifeInMotion", "#CityEscape"],
    accent: "#4fc3f7",
    bg: "#1a2636",
    icon: "city",
    paper: "#e9f3fa",
    frameLabels: { route: "MY NEXT STOP", postcard: "POSTCARD FROM", window: "VIEW FROM MY JOURNEY" },
    copy: { stop: "ESCAPING TO NEXT", place: "MY CITY ESCAPE", view: "VIEW FROM THE SKYLINE" },
  },
  {
    month: 5,
    name: "五月",
    season: "SUMMER",
    title: "COASTLINE DRIVE",
    tagline: "Salt air, open windows, endless road.",
    hashtags: ["#KaiyiLifeInMotion", "#CoastlineDrive"],
    accent: "#ffc93c",
    bg: "#103a4a",
    icon: "wave",
    paper: "#fdf4e0",
    frameLabels: { route: "MY NEXT STOP", postcard: "POSTCARD FROM", window: "VIEW FROM MY JOURNEY" },
    copy: { stop: "NEXT SEASIDE STOP", place: "MY COASTLINE", view: "VIEW FROM THE SHORE" },
  },
  {
    month: 6,
    name: "六月",
    season: "SUMMER",
    title: "MOUNTAIN BREEZE",
    tagline: "Climb higher, breathe deeper.",
    hashtags: ["#KaiyiLifeInMotion", "#MountainBreeze"],
    accent: "#9be15d",
    bg: "#24331f",
    icon: "mountain",
    paper: "#edf6e6",
    frameLabels: { route: "MY NEXT STOP", postcard: "POSTCARD FROM", window: "VIEW FROM MY JOURNEY" },
    copy: { stop: "NEXT SUMMIT STOP", place: "MY MOUNTAIN", view: "VIEW FROM THE TOP" },
  },
  {
    month: 7,
    name: "七月",
    season: "SUMMER",
    title: "SUMMER ROADTRIP",
    tagline: "Long miles, golden hour, best music.",
    hashtags: ["#KaiyiLifeInMotion", "#SummerRoadtrip"],
    accent: "#ff8a3d",
    bg: "#402018",
    icon: "sunset",
    paper: "#fcf0e6",
    frameLabels: { route: "MY NEXT STOP", postcard: "POSTCARD FROM", window: "VIEW FROM MY JOURNEY" },
    copy: { stop: "NEXT ROADTRIP STOP", place: "MY SUMMER ROUTE", view: "VIEW FROM MY ROADTRIP" },
  },
  {
    month: 8,
    name: "八月",
    season: "SUMMER",
    title: "DESERT SUNSET",
    tagline: "Where the road meets the dunes.",
    hashtags: ["#KaiyiLifeInMotion", "#DesertSunset"],
    accent: "#ffb199",
    bg: "#3d2b1e",
    icon: "dune",
    paper: "#fbeede",
    frameLabels: { route: "MY NEXT STOP", postcard: "POSTCARD FROM", window: "VIEW FROM MY JOURNEY" },
    copy: { stop: "NEXT DUNE STOP", place: "MY DESERT", view: "VIEW FROM THE DUNES" },
  },
  {
    month: 9,
    name: "九月",
    season: "AUTUMN",
    title: "SHARE YOUR DESTINATION",
    tagline: "Every departure is worth remembering.",
    hashtags: ["#KaiyiLifeInMotion", "#ShareYourDestination"],
    accent: "#c8f24a",
    bg: "#0a1220",
    icon: "maple",
    paper: "#f6efe2",
    frameLabels: { route: "MY NEXT STOP", postcard: "POSTCARD FROM", window: "VIEW FROM MY JOURNEY" },
    copy: { stop: "MY NEXT STOP", place: "MY DESTINATION", view: "VIEW FROM MY JOURNEY" },
  },
  {
    month: 10,
    name: "十月",
    season: "AUTUMN",
    title: "AUTUMN COLORS",
    tagline: "Turn every mile into a painting.",
    hashtags: ["#KaiyiLifeInMotion", "#AutumnColors"],
    accent: "#f7a83c",
    bg: "#3a2a16",
    icon: "leaf",
    paper: "#f8f0e0",
    frameLabels: { route: "MY NEXT STOP", postcard: "POSTCARD FROM", window: "VIEW FROM MY JOURNEY" },
    copy: { stop: "NEXT COLORFUL STOP", place: "MY AUTUMN MAP", view: "VIEW FROM THE FOLIAGE" },
  },
  {
    month: 11,
    name: "十一月",
    season: "AUTUMN",
    title: "MISTY LAKE",
    tagline: "Quiet water, quieter mind.",
    hashtags: ["#KaiyiLifeInMotion", "#MistyLake"],
    accent: "#8ec5e8",
    bg: "#1e2a38",
    icon: "mist",
    paper: "#eaeff4",
    frameLabels: { route: "MY NEXT STOP", postcard: "POSTCARD FROM", window: "VIEW FROM MY JOURNEY" },
    copy: { stop: "NEXT QUIET STOP", place: "MY MISTY LAKE", view: "VIEW FROM THE MIST" },
  },
  {
    month: 12,
    name: "十二月",
    season: "WINTER",
    title: "WINTER WONDERLAND",
    tagline: "Fresh snow, warm memories.",
    hashtags: ["#KaiyiLifeInMotion", "#WinterWonderland"],
    accent: "#bfe4ff",
    bg: "#18222e",
    icon: "snowflake",
    paper: "#edf3f8",
    frameLabels: { route: "MY NEXT STOP", postcard: "POSTCARD FROM", window: "VIEW FROM MY JOURNEY" },
    copy: { stop: "NEXT SNOWY STOP", place: "MY WINTER WONDERLAND", view: "VIEW FROM THE SNOW" },
  },
];

// 相框模板的说明信息
export const FRAME_INFO = {
  route: { no: "01", name: "路线打卡", desc: "在照片上叠加线路标记与「下一站」标语" },
  postcard: { no: "02", name: "旅行明信片", desc: "明信片式排版，带主题标题与月序徽章" },
  window: { no: "03", name: "车窗视角", desc: "模拟车窗取景框，营造旅程第一视角" },
};

export const getMonthTheme = (month) =>
  THEMES.find((t) => t.month === month) || THEMES[8];

export const DEFAULT_MONTH = 9;
export const DEFAULT_THEME = getMonthTheme(DEFAULT_MONTH);
